import './globals.css'
import { Jua } from 'next/font/google'

const inter = Jua({ subsets: ['latin'] ,weight:'400'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}
        
      </body>
    </html>
  )
}
